Title: Hupload Test
default_validity_days: 12
default_exposure: download
storage:
  type: file
  options:
    path: tmptest/data
    max_file_mb: 3
    max_share_mb: 5
auth:
  type: file
  options:
    path: handlers_testdata/users.yml
messages:
  - title: Message title
    message: |
      Message content