services:
  hupload:
    image: ghcr.io/ybizeul/hupload/hupload:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./hupload/config/config.yml.sample:/config.yml
      - ./hupload/config/users.yml.sample:/users.yml
  