title: Hupload
default_validity_days: 12
default_exposure: download
hide_other_shares: true
auth:
  type: file
  options:
    path: config_testdata/users.yml
storage:
  type: file
  options:
    path: data
    max_file_mb: 500
    max_share_mb: 2000
messages:
  - title: Message title
    message: |
      Message content