on:
  push:
    branches:
      - main
  
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Fetch tags
      - run: git fetch --force --tags
      
      # Set version environment
      - name: Set VERSION
        run: |
          echo "VERSION=`git describe --tags || echo 0.0.0`"  >> $GITHUB_ENV

      # Build web ui
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - run: yarn install
        working-directory: ./html
      - run: yarn build --outDir ../hupload/admin-ui
        working-directory: ./html

      # Build docker image
      - uses: ko-build/setup-ko@v0.6
      - run: GOFLAGS="-ldflags=-X=main.version=$VERSION" ko build -B --platform all --sbom none
        working-directory: ./hupload
